name: monorepo-poc

version: "3"

services:
  my-microservice:
    image: ghcr.io/my-namespace/my-microservice:${MY_MICROSERVICE_VERSION:-dev}
    command: ["/app/dist/main.js"]
    ports:
      - "3000:80"
    environment:
      PORT: 80
      OTHER_HOST: http://other-microservice
  other-microservice:
    image: ghcr.io/my-namespace/other-microservice:${OTHER_MICROSERVICE_VERSION:-dev}
    command: ["/app/dist/main.js"]
    environment:
      PORT: 80
