# This is the dev docker compose profile. It replaces the production image of each service with the dev image and mounts
# your local monorepo into each container, enabling hot reloading for all services.
services:
  my-microservice:
    image: ghcr.io/my-namespace/monorepo:dev
    command: ["pnpm", "--filter", "my-microservice", "dev"]
    volumes:
      - ../:/monorepo
    ports:
      - "3000:80"
  other-microservice:
    image: ghcr.io/my-namespace/monorepo:dev
    command: ["pnpm", "--filter", "other-microservice", "dev"]
    volumes:
      - ../:/monorepo
  my-react-app:
    image: ghcr.io/my-namespace/monorepo:dev
    command: ["pnpm", "--filter", "my-react-app", "dev", "--host", "0.0.0.0"]
    volumes:
      - ../:/monorepo
    ports:
      - "5000:5173"
