# This is a base docker compose profile. Other profiles will extend this profile to create various deployments of the
# stack. The best way to use this infrastructure is through the `pnpm docker:compose` command. See
# `pnpm docker:compose --help` more details.
name: monorepo-poc

version: "3"

services:
  my-microservice:
    image: ghcr.io/my-namespace/my-microservice:${MY_MICROSERVICE_VERSION:-dev}
    command: ["/app/dist/main.js"]
    environment:
      PORT: 80
      OTHER_HOST: http://other-microservice
  other-microservice:
    image: ghcr.io/my-namespace/other-microservice:${OTHER_MICROSERVICE_VERSION:-dev}
    command: ["/app/dist/main.js"]
    environment:
      PORT: 80
  my-react-app:
    image: ghcr.io/my-namespace/my-react-app:${MY_REACT_APP_VERSION:-dev}
